### ISSUE TITLE
(exit) exited in: GenServer.call(:"test spawns buckets", {:create, "shopping"}, 5000)

### ISSUE THREAD

**Issue by dapperAuteur** [josevalim/kv_umbrella#1]
I'm at the end of the ETS section of the tutorial, page 89 of the epub document. I get this error for 3 of my tests.

`1) test spawns buckets (KV.RegistryTest)
     test/kv/registry_test.exs:9
     ** (exit) exited in: GenServer.call(:"test spawns buckets", {:create, "shopping"}, 5000)
         ** (EXIT) an exception was raised:
             ** (ErlangError) Erlang error: :timeout_value
                 (stdlib) gen_server.erl:389: :gen_server.loop/7
                 (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
     code: KV.Registry.create(registry, "shopping")
     stacktrace:
       (elixir) lib/gen_server.ex:774: GenServer.call/3
       test/kv/registry_test.exs:12: (test)`
The tests that fail are; 'test spawns buckets', 'test removes buckets on exit', 'test removes buckets on crash'. This is my registry_test.exs file:
`defmodule KV.RegistryTest do
  use ExUnit.Case, async: true

  setup context do
    {:ok, _} = start_supervised({KV.Registry, name: context.test})
    %{registry: context.test}
  end

  test "spawns buckets", %{registry: registry} do
    assert KV.Registry.lookup(registry, "shopping") == :error

    KV.Registry.create(registry, "shopping")
    assert {:ok, bucket} = KV.Registry.lookup(registry, "shopping")

    KV.Bucket.put(bucket, "milk", 1)
    assert KV.Bucket.get(bucket, "milk") == 1
  end

  test "removes buckets on exit", %{registry: registry} do
    KV.Registry.create(registry, "shopping")
    {:ok, bucket} = KV.Registry.lookup(registry, "shopping")
    Agent.stop(bucket)

    # Do a call to ensure the registry processed the DOWN message
    _ = KV.Registry.create(registry, "bogus")
    assert KV.Registry.lookup(registry, "shopping") == :error
  end

  test "removes bucket on crash", %{registry: registry} do
    KV.Registry.create(registry, "shopping")
    {:ok, bucket} = KV.Registry.lookup(registry, "shopping")

    # Stop the bucket with non-normal reason
    Agent.stop(bucket, :shutdown)

    # Do a call to ensure the registry processed the DOWN message
    _ = KV.Registry.create(registry, "bogus")
    assert KV.Registry.lookup(registry, "shopping") == :error
  end

end
`

**Comment by josevalim** [comment]
Can you push your code somewhere?
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by dapperAuteur** [comment]
I resolved it.

**Comment by dapperAuteur** [comment]
I forgot to change  the handle_call function to ':reply'. It still was on ':noreply'. Thanks for your quick response. Love elixir and the tutorial.
