### ISSUE TITLE
“elixir --sname foo -S mix test” won't run tests

### ISSUE THREAD

**Issue by dapperAuteur** [josevalim/kv_umbrella#3]
When attempting to run the test I get the following response:
```
Protocol 'inet_tcp': the name foo@awefulBrowns-MacBook-Air seems to be in use by another Erlang node
```

Am I doing it wrong?
Also, can ```iex --sname bar -S mix``` and ```iex --sname foo -S mix``` be run in the same directory? I get a nasty message when I attempt to run them in the same directory.

**Comment by josevalim** [comment]
You probably have another instance of the Erlang VM running with the same name in your machine. You can consult the activity manager and try to terminate any OS process with beam as name.

Given those are not issues with the tutorial but rather a request for help, could you please use the ElixirForum or the mailing list for guidance? Unfortunately I cannot individually help all users learning the language. :) Thanks!

**Comment by dapperAuteur** [comment]
Thank you. I was under the impression that both iex --sname bar -S mix and iex --sname foo -S mix needed to be running for the tests to work properly. That's not the case.
